import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import SideBar from "./component/common/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full h-full mx-10 mt-10">
          <div className="w-[20%] h-full">
            <SideBar />
          </div>
          <div className="w-[80%] h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
